version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "9080:80"
      - "9000:443"
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./docker/ssl:/etc/ssl
      - ./:/usr/share/nginx/html
  php:
    image: php:8.2-fpm
    build:
      context: ./docker/php
    restart: always
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:delegated"
      - "./:/var/www:cached"
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_DATABASE=laravel_base
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=dbpassword
      - MARIADB_ROOT_PASSWORD=dbrootpassword
